---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  sudo_command: sudo -E -H
  require_pip: true
  ansible_verbose: true
  ansible_verbosity: 1
  ansible_version: 2.2.0.0
  require_chef_for_busser: false
  require_ruby_for_busser: true
  additional_copy_path: playbooks
  ansible_connection: ssh
  roles_path: .
  playbook: site.yml

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
      platform: ubuntu

verifier:
  name: busser
  plugin:
    - Ansiblespec
  ruby_bindir: '/usr/bin'

suites:
  - name: percona_server
    provisioner:
    playbook: test/integration/percona_server/percona_server_test.yml
    additional_copy_path:
      - "."
